### PR TITLE
remove duplicate code

### PR DESCRIPTION
**Pull request by joycehwchan**

### CODE REVIEW

**Review by hafid-Qa — COMMENTED** [review]
Are you able to get directed to log in before creating booking after removing the the else statement

**Comment by joycehwchan** [comment]
@hafid-Qa  I removed a duplicated else statement. That fixes the template error.

**Comment by joycehwchan** [comment]
@hafid-Qa I removed a duplicated else statement. The button display doesn't change.

**Comment by hafid-Qa** [comment]
Ah ok didn't pay attention that I pasted the code twice

**Pull request merged**
